spring.application.name=chat-microservice

###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip=${DB_IP:localhost}
database.port=${DB_PORT:5432}
database.user=${DB_USER:postgres}
database.password=${DB_PASSWORD:monica1234}
database.name=${DB_DBNAME:chat-db}

spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username=${database.user}
spring.datasource.password=${database.password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

###############################################
### RABBITMQ CONFIGURATION ###
###############################################
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

###############################################
### LOGGING ###
###############################################
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.com.example=DEBUG

###############################################
### SECURITY (JWT) ###
###############################################
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=1800000

###############################################
### SERVER CONFIGURATION ###
###############################################
server.port=${PORT:8085}
server.tomcat.threads.max=1

###############################################
### AI API Call ###
###############################################
#You can use your own api key by saving it here as gemini.api.key 
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent