# ----------------------------------------
# CORE CONFIGURATION
# ----------------------------------------
spring.application.name=websocket-microservice
server.port=${PORT:8084}

# ----------------------------------------
# RABBITMQ CONFIGURATION
# ----------------------------------------
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# ----------------------------------------
# LOGGING
# ----------------------------------------
logging.level.root=INFO
logging.level.org.springframework.web.socket=INFO
logging.level.org.springframework.messaging=INFO